### ISSUE TITLE
M1 inputs need scaling within the tpl to account for Nstepsyr

### ISSUE THREAD

**Issue by sgaichas** [thefaylab/hydra_sim#25]
I believe annual M1 is intended to be 0.1 for all species and sizebins, at least as a start.

The original `hydradata` inputs implicitly assumed 5 steps per year, approximating annual M1=0.1 by inputting M1=0.02. 5 steps per year was correct for original hydra_sim and happens to be correct for the NOBA 5 bin dataset.

The real GB dataset has 1 step per year with the growth functions and sizebins we input. (so M1=0.02 is lower than we intended)

The NOBA 10 bin dataset has 18 (!) steps per year. (so M1=0.02 is higher than we intended)

**Comment by sgaichas** [comment]
@gavinfay perhaps the best way forward is to input the desired annual M1 at length for each species, currently 0.1 across all lengths, then apply

M1step = 1 - (1-M1)^(1/Nstepsyr)

after `Nstepsyr` is calculated in the tpl in the data section. I can make this change as long as it doesn't mess you up. (and if it looks correct to you)

**Comment by sgaichas** [comment]
Added code to rescale M1: 7db40d5f066bdee2fd977da0f1f6101e5d9d346e
M1 = 0.1 in all current .dat files: d0e6e561cb0b7071045df862364e041bba44603a
M1 = 0.1 in all current hydraDataList files: 5d7959b5a9be638d11a91a7cc7b6d59479a19c3d
changed default M1 in `hydradata`: [0cd5d967407ac17878887f210b82dc50de3cae70](https://github.com/thefaylab/hydradata/commit/0cd5d967407ac17878887f210b82dc50de3cae70)

**Comment by gavinfay** [comment]
Aah! This change looks great. Thanks!
