### ISSUE TITLE
NAs in NOBA data file

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/hydra_sim#6]
Using this issue to tag locations of NAs in the NOBA data file(s).

I see one in `hydra_sim_NOBA.dat` for species 6 in the VB Linfinity:
`init_matrix vonB_Linf`

**Comment by gavinfay** [comment]
All matrices in `hydra_sim_NOBA-ts.dat` have `NAs` in the `survey` & `spp` columns. Guessing this was a result of changing from character strings?

**Comment by sgaichas** [comment]
Sorry! Those worked as conversions to numeric before, I need to check what went wrong.

**Comment by sgaichas** [comment]
@gavinfay I was caught by the different R version strings-as-factors defaults... should be fixed now

**Comment by sgaichas** [comment]
fixed in https://github.com/thefaylab/hydra_sim/commit/a74bc5b7130d36cb880651ae5b245a71d09caaf8
with code in https://github.com/thefaylab/hydradata/commit/ac70311087469644ff1d0213d06aac73b21ee8e3

**Comment by gavinfay** [comment]
Marvelous! Thanks!
