### ISSUE TITLE
realign year indexing in NOBA data files

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/hydra_sim#9]
Years in hydra are indexed from 1:Nyears
Recent shift in number of years of output data from the NOBA Atlantis simulations creates a mismatch between Atlantis years and hydra years.
@sgaichas can you adjust the simulated data files for hydra so that the input files based on these data will adjust the indexing for years depending on the start year of the output in the data files rather than the original Atlantis run?
Thanks!

**Comment by sgaichas** [comment]
@gavinfay should be fixed now with https://github.com/thefaylab/hydra_sim/commit/7ad16194e6a276f162379bf9ba7848d229540b06

methods are in https://ices-eg.github.io/wg_WGSAM/SkillAssessProject.html

and updated data in https://github.com/thefaylab/hydradata
